export const LEAK_WORLD_CREATORS = [
  { rank: 1, name: 'Sophie Rain', marketRead: 'Current top demand, massive news cycle, reported $50M plus profit' },
  { rank: 2, name: 'Mia Khalifa', marketRead: 'Highest evergreen search demand, huge mainstream recognition' },
  { rank: 3, name: 'Bhad Bhabie', marketRead: 'Verified viral earnings story, huge mainstream search demand' },
  { rank: 4, name: 'Bella Thorne', marketRead: 'Celebrity OF launch legend, still highly searched' },
  { rank: 5, name: 'Blac Chyna', marketRead: 'Legacy top earner narrative, celebrity demand' },
  { rank: 6, name: 'Iggy Azalea', marketRead: 'Music celebrity plus subscription monetization' },
  { rank: 7, name: 'Cardi B', marketRead: 'Celebrity fan access model' },
  { rank: 8, name: 'Tana Mongeau', marketRead: 'YouTube and controversy driven demand' },
  { rank: 9, name: 'Belle Delphine', marketRead: 'Meme culture, scarcity, internet native demand' },
  { rank: 10, name: 'Tyga', marketRead: 'Male celebrity OF demand' },
  { rank: 11, name: 'Amber Rose', marketRead: 'Celebrity adult creator demand' },
  { rank: 12, name: 'Bonnie Blue', marketRead: 'Huge 2025 controversy and search spike' },
  { rank: 13, name: 'Lily Phillips', marketRead: 'Viral stunt based demand' },
  { rank: 14, name: 'Ari Kytsya', marketRead: 'Mainstream brand crossover plus OF identity' },
  { rank: 15, name: 'Camilla Araujo', marketRead: 'MrBeast, YouTube, Bop House, OF earnings narrative' },
  { rank: 16, name: 'Aishah Sofey', marketRead: 'Bop House cofounder, social reach' },
  { rank: 17, name: 'Angela White', marketRead: 'Adult industry name recognition' },
  { rank: 18, name: 'Mia Malkova', marketRead: 'Adult industry plus social demand' },
  { rank: 19, name: 'Eva Elfie', marketRead: 'International adult search demand' },
  { rank: 20, name: 'Francesca Farago', marketRead: 'Netflix reality celebrity crossover' },
  { rank: 21, name: 'Lena Nersesian / Lena The Plug', marketRead: 'YouTube, podcast, adult creator search demand' },
  { rank: 22, name: 'Amouranth', marketRead: 'Twitch, influencer, subscription creator crossover' },
  { rank: 23, name: 'Corinna Kopf', marketRead: 'Influencer and OF earnings history' },
  { rank: 24, name: 'Coco Austin', marketRead: 'Celebrity glamour demand' },
  { rank: 25, name: 'Trisha Paytas', marketRead: 'YouTube celebrity plus OF earnings lists' },
  { rank: 26, name: 'Pia Mia', marketRead: 'Celebrity earner lists' },
  { rank: 27, name: 'Ana Cheri', marketRead: 'Fitness, modeling, evergreen Instagram demand' },
  { rank: 28, name: 'Francia James', marketRead: 'High social reach, adult creator demand' },
  { rank: 29, name: 'Violet Myers', marketRead: 'Strong adult search demand' },
  { rank: 30, name: 'Bryce Adams', marketRead: 'High OF platform recognition' },
  { rank: 31, name: 'Louisa Khovanski', marketRead: 'Instagram and model search demand' },
  { rank: 32, name: 'Skylar Mae', marketRead: 'High recurring OF discovery demand' },
  { rank: 33, name: 'Bruna Lima', marketRead: 'Fitness and glamour market' },
  { rank: 34, name: 'Kayleigh Swenson / Viking Barbie', marketRead: 'Music, alt model, OF demand' },
  { rank: 35, name: 'Emily Elizabeth', marketRead: 'Instagram model demand' },
  { rank: 36, name: 'Hannah Palmer', marketRead: 'Instagram glamour demand' },
  { rank: 37, name: 'Kayla Simmons', marketRead: 'Athlete influencer plus OF search' },
  { rank: 38, name: 'Ariella Ferrera', marketRead: 'Adult industry recognition' },
  { rank: 39, name: 'Whitney Johns', marketRead: 'Fitness creator segment' },
  { rank: 40, name: 'Carriejune Anne Bowlby', marketRead: 'Fitness creator segment' },
  { rank: 41, name: 'Heidi Lavon', marketRead: 'Tattoo, alt model niche' },
  { rank: 42, name: 'Gigi Gorgeous Getty', marketRead: 'LGBTQ creator and celebrity demand' },
  { rank: 43, name: 'Kerry Katona', marketRead: 'UK celebrity OF demand' },
  { rank: 44, name: 'Drea de Matteo', marketRead: 'Mainstream actor OF news demand' },
  { rank: 45, name: 'Sonja Morgan', marketRead: 'Reality TV OF demand' },
  { rank: 46, name: 'Chloe Sims', marketRead: 'UK reality TV OF demand' },
  { rank: 47, name: 'Renee Gracie', marketRead: 'Motorsports and adult creator story' },
  { rank: 48, name: 'Brittney Palmer', marketRead: 'UFC model crossover' },
  { rank: 49, name: 'Amanda Ribas', marketRead: 'Combat sports crossover' },
  { rank: 50, name: 'Polyana Viana', marketRead: 'Combat sports crossover' },
  { rank: 51, name: 'Maryana Ro', marketRead: 'Influencer demand' },
  { rank: 52, name: 'Yeri Mua', marketRead: 'Latin creator demand' },
  { rank: 53, name: 'Danyan Cat', marketRead: 'Latin influencer demand' },
  { rank: 54, name: 'Marleny Aleelayn', marketRead: 'Latin creator demand' },
  { rank: 55, name: 'Daniela Alexis', marketRead: 'Reality and influencer demand' },
  { rank: 56, name: 'Emily Ahern', marketRead: 'Influencer creator demand' },
  { rank: 57, name: 'Sofia Gomez', marketRead: 'TikTok and creator demand' },
  { rank: 58, name: 'Nara Ford', marketRead: 'Creator search demand' },
  { rank: 59, name: 'Janna Breslin', marketRead: 'Fitness creator demand' },
  { rank: 60, name: 'Marcela Moss', marketRead: 'Latin model niche' },
  { rank: 61, name: 'Brandi Andrews', marketRead: 'Creator ranking visibility' },
  { rank: 62, name: 'Sydney Lint', marketRead: 'Creator ranking visibility' },
  { rank: 63, name: 'Lexi Cayla', marketRead: 'Creator ranking visibility' },
  { rank: 64, name: 'Diana Maux', marketRead: 'Creator ranking visibility' },
  { rank: 65, name: 'Jasmine Gifford', marketRead: 'Model and influencer demand' },
  { rank: 66, name: 'Molly Eskam', marketRead: 'YouTube and modeling crossover' },
  { rank: 67, name: 'Corinne Olympios', marketRead: 'Reality TV crossover' },
  { rank: 68, name: 'Casey Boonstra', marketRead: 'Model and influencer demand' },
  { rank: 69, name: 'CJ Sparxx', marketRead: 'Adult creator demand' },
  { rank: 70, name: 'Sugey Abrego', marketRead: 'Spanish language celebrity demand' },
  { rank: 71, name: 'Carla Leclercq', marketRead: 'Fitness and model demand' },
  { rank: 72, name: 'Lizzy Capri', marketRead: 'YouTube creator crossover' },
  { rank: 73, name: 'Vic Hoa', marketRead: 'Creator ranking visibility' },
  { rank: 74, name: 'Willow Harper', marketRead: 'Creator ranking visibility' },
  { rank: 75, name: 'Alyssa Griffith', marketRead: 'Creator ranking visibility' },
  { rank: 76, name: 'Ashleigh Dunn', marketRead: 'Creator ranking visibility' },
  { rank: 77, name: 'Jasmin Montalvo', marketRead: 'Creator ranking visibility' },
  { rank: 78, name: 'Kellan Ness', marketRead: 'Male creator niche' },
  { rank: 79, name: 'Diana Estrada', marketRead: 'Creator ranking visibility' },
  { rank: 80, name: 'Aniela Verbin', marketRead: 'Creator ranking visibility' },
  { rank: 81, name: 'Tati Evans', marketRead: 'Creator ranking visibility' },
  { rank: 82, name: 'Shayne Jansen', marketRead: 'Reality TV crossover' },
  { rank: 83, name: 'Sabrina Banks', marketRead: 'Adult creator demand' },
  { rank: 84, name: 'Courtney McClure', marketRead: 'Creator ranking visibility' },
  { rank: 85, name: 'Cathilee Zingano', marketRead: 'Combat sports crossover' },
  { rank: 86, name: 'Lewis Buchanan', marketRead: 'Male fitness creator niche' },
  { rank: 87, name: 'Sarah Caldeira', marketRead: 'Creator ranking visibility' },
  { rank: 88, name: 'Jade Love', marketRead: 'Creator ranking visibility' },
  { rank: 89, name: 'Lacey Jayne', marketRead: 'Creator ranking visibility' },
  { rank: 90, name: 'Mila', marketRead: 'Creator ranking visibility' },
  { rank: 91, name: 'Tara', marketRead: 'Creator ranking visibility' },
  { rank: 92, name: 'Angelina Maldonado', marketRead: 'Creator ranking visibility' },
  { rank: 93, name: 'Samantha Jerasa', marketRead: 'Creator ranking visibility' },
  { rank: 94, name: 'Callie Murphy', marketRead: 'Creator ranking visibility' },
  { rank: 95, name: 'Summer Brookes', marketRead: 'Creator ranking visibility' },
  { rank: 96, name: 'Elena Belle', marketRead: 'Reality and glamour demand' },
  { rank: 97, name: 'SlimGem24', marketRead: 'Creator ranking visibility' },
  { rank: 98, name: 'Lexi Luna', marketRead: 'Adult industry search demand' },
  { rank: 99, name: 'Johnny Sins', marketRead: 'Male adult search demand' },
  { rank: 100, name: 'Alex Adams', marketRead: 'Male OF and adult ranking demand' },
];
